"""add_composite_indexes

Revision ID: 36bb81630e7b
Revises: 78fb0b48a8b4
Create Date: 2026-02-09 00:22:41.645875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bb81630e7b'
down_revision: Union[str, None] = '78fb0b48a8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alert_active_field_event', 'alerts', ['is_active', 'field_id', 'event_type'], unique=False)
    op.create_index('ix_weather_field_event_date', 'weather_data', ['field_id', 'event_type', 'target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_field_event_date', table_name='weather_data')
    op.drop_index('ix_alert_active_field_event', table_name='alerts')
    # ### end Alembic commands ###
